#!/bin/bash
# GeminiとCodexでIssueをレビューし結果をコメント投稿する。
#
# Why:
#     AIによるIssueレビューを自動化し、
#     問題の明確さや技術的実現性を事前に検証するため。
#
# What:
#     - run_gemini_review(): Gemini CLIでレビュー実行
#     - run_codex_review(): Codex CLIでレビュー実行
#     - gh issue comment: レビュー結果を投稿
#
# Remarks:
#     - Usage: issue-ai-review.sh <issue_number>
#     - 並列実行で両方のレビューを取得
#     - CLIが無い場合はスキップ（graceful degradation）
#     - set -eを使用しないのはエラーハンドリングのため
#
# Changelog:
#     - silenvx/dekita#1600: IssueのAIレビュー機能を追加

# Note: We use set -uo pipefail but not -e because we handle errors explicitly
# with || patterns for graceful degradation when AI tools are unavailable
set -uo pipefail

ISSUE_NUMBER="${1:-}"
if [[ -z "$ISSUE_NUMBER" ]]; then
    echo "Usage: $0 <issue_number>" >&2
    exit 1
fi

# Get issue content (using jq to safely escape all values)
ISSUE_JSON=$(gh issue view "$ISSUE_NUMBER" --json title,body,labels 2>/dev/null) || {
    echo "Failed to fetch issue #$ISSUE_NUMBER" >&2
    exit 1
}

if [[ -z "$ISSUE_JSON" || "$ISSUE_JSON" == "null" ]]; then
    echo "Empty response for issue #$ISSUE_NUMBER" >&2
    exit 1
fi

# Build review prompt using jq to safely handle special characters
# This prevents shell injection from issue title/body content
REVIEW_PROMPT=$(jq -r --arg prompt "$(cat <<'PROMPT_EOF'
以下のGitHub Issueをレビューしてください。

レビュー観点:
1. 問題の明確さ: 問題が具体的に説明されているか
2. 再現手順: 問題を再現するための情報が十分か
3. 期待動作: 期待される動作が明確か
4. 技術的実現性: 提案された解決策は妥当か
5. 優先度の妥当性: ラベルや説明から優先度は適切か

改善提案があれば具体的に指摘してください。

---
PROMPT_EOF
)" '
    $prompt + "\n# " + .title + "\n\n" + (.body // "") + "\n\nLabels: " + ([.labels[].name] | join(", "))
' <<< "$ISSUE_JSON")

# Temporary files for parallel execution
GEMINI_RESULT=$(mktemp)
CODEX_RESULT=$(mktemp)
cleanup() {
    rm -f "$GEMINI_RESULT" "$CODEX_RESULT"
}
trap cleanup EXIT

# Sentinel values for detecting failures
readonly GEMINI_UNAVAILABLE="__GEMINI_CLI_NOT_AVAILABLE__"
readonly GEMINI_FAILED="__GEMINI_REVIEW_FAILED__"
readonly CODEX_UNAVAILABLE="__CODEX_CLI_NOT_AVAILABLE__"
readonly CODEX_FAILED="__CODEX_REVIEW_FAILED__"

# Run Gemini review (if available)
run_gemini_review() {
    if ! command -v gemini &>/dev/null; then
        echo "$GEMINI_UNAVAILABLE"
        return 0
    fi
    local output
    if output=$(echo "$REVIEW_PROMPT" | gemini -p "あなたはGitHub Issueレビューアーです。簡潔に日本語でレビューしてください。" 2>/dev/null); then
        echo "$output"
    else
        echo "$GEMINI_FAILED"
    fi
}

# Run Codex review (if available)
run_codex_review() {
    if ! command -v codex &>/dev/null; then
        echo "$CODEX_UNAVAILABLE"
        return 0
    fi
    local output
    # codex exec reads prompt from stdin when using '-'
    # System instructions are included in the prompt itself
    local codex_prompt="あなたはGitHub Issueレビューアーです。簡潔に日本語でレビューしてください。

$REVIEW_PROMPT"
    if output=$(echo "$codex_prompt" | timeout 120 codex exec - 2>/dev/null); then
        echo "$output"
    else
        echo "$CODEX_FAILED"
    fi
}

# Run reviews in parallel
run_gemini_review > "$GEMINI_RESULT" &
GEMINI_PID=$!

run_codex_review > "$CODEX_RESULT" &
CODEX_PID=$!

# Wait for both to complete (exit status handled by sentinel values)
wait "$GEMINI_PID" 2>/dev/null
wait "$CODEX_PID" 2>/dev/null

GEMINI_OUTPUT=$(cat "$GEMINI_RESULT")
CODEX_OUTPUT=$(cat "$CODEX_RESULT")

# Check if we have any useful review output
gemini_useful=false
codex_useful=false

if [[ "$GEMINI_OUTPUT" != "$GEMINI_UNAVAILABLE" && "$GEMINI_OUTPUT" != "$GEMINI_FAILED" && -n "$GEMINI_OUTPUT" ]]; then
    gemini_useful=true
fi

if [[ "$CODEX_OUTPUT" != "$CODEX_UNAVAILABLE" && "$CODEX_OUTPUT" != "$CODEX_FAILED" && -n "$CODEX_OUTPUT" ]]; then
    codex_useful=true
fi

# Skip posting if neither review produced useful output
if [[ "$gemini_useful" == "false" && "$codex_useful" == "false" ]]; then
    echo "No useful AI review output to post" >&2
    exit 0
fi

# Build comment with only successful reviews
COMMENT="## 🤖 AI Review

"

if [[ "$gemini_useful" == "true" ]]; then
    COMMENT+="### Gemini Review
$GEMINI_OUTPUT

"
fi

if [[ "$codex_useful" == "true" ]]; then
    COMMENT+="### Codex Review
$CODEX_OUTPUT

"
fi

COMMENT+="---
*This review was automatically generated by issue-ai-review hook.*"

# Post comment to issue
if gh issue comment "$ISSUE_NUMBER" --body "$COMMENT"; then
    echo "AI review posted to issue #$ISSUE_NUMBER"
else
    echo "Failed to post comment to issue #$ISSUE_NUMBER" >&2
    exit 1
fi
